boe/urls.py
from django.db.models import base
from django.urls import include, path
from django.contrib import admin
from rest_framework import routers
from api.views import *
from api.views import callistadatafile


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
router = routers.DefaultRouter()
router.register(r'faculties', faculty.FacultyViewSet, basename='faculty')
router.register(r'students', student.StudentViewSet, basename="student")
router.register(r'courses', course.CourseViewSet, basename="course")
router.register(r'coursemodules',
                coursemodule.CourseModuleViewSet, basename="coursemodule")
router.register(r'wrapper', wrapper.WrapperViewSet, basename="wrapper")
router.register(r'corelists', corelist.CoreListViewSet, basename="corelist")
router.register(r'cores', core.CoreViewSet, basename="core")
router.register(r'electivelist', electivelist.ElectiveListViewSet,
                basename="electivelist")
router.register(r'electives', elective.ElectiveViewSet,
                basename="elective")
router.register(r'units', unit.UnitViewSet, basename="unit")
router.register(r'enrolments', enrolment.EnrolmentViewSet,
                basename="enrolment")
router.register(r'callista', callistadatafile.CallistaDataFileViewSet,
                basename="callista")
router.register(r'users', user.UserViewSet, basename="user")
urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include('checkerapp.urls'))
]

checkerapp/urls.py
from django.urls import path, include
from . import views
app_name = 'checkerapp'

urlpatterns = [
    path('', views.CallistaDataFileCreateView.as_view(), name='upload'),
    path('processor/', views.processor, name='processor'),
    path('validator/', views.validator, name='validator'),
    path('download/', views.download, name='download')
]

checkerapp/models.py
from django.db import models

# Create your models here.

checkerapp/forms.py
from django import forms


class CallistaDataFileMultipleUploadForm(forms.Form):
    name = forms.CharField(max_length=50)
    uploads = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))

checkerapp/views.py
import os
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.edit import FormView
from api.models import CallistaDataFile, Student
from checkerapp.forms import CallistaDataFileMultipleUploadForm
from api.models import CallistaDataFile
import scripts.process_csv as pc
import pandas as pd
from django.conf import settings
from django.http import Http404

user_to_output = dict()
file_path = os.path.join(os.path.join(
    settings.MEDIA_ROOT, "downloads"), f"report.csv")


class CallistaDataFileCreateView(FormView):
    form_class = CallistaDataFileMultipleUploadForm
    template_name = 'checkerapp_upload_form.html'

    def get_success_url(self) -> str:
        return reverse('checkerapp:processor')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('uploads')
        if form.is_valid():
            for csv in files:
                print(form.cleaned_data)
                # add each CSV as an callista object
                obj = CallistaDataFile.objects.create(
                    name=form.cleaned_data['name'],
                    upload=csv
                )
                print(obj)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def processor(request):
    global user_to_output
    if request.method == "POST":
        files_posted = []
        for key, value in request.POST.items():
            if value == '1':
                files_posted.append(int(key))
        print("files_posted: ", files_posted)
        student_set = set()
        for file in CallistaDataFile.objects.filter(pk__in=files_posted):
            student_set.update(pc.bulk_pc(file))
            file.has_been_processed = True
            file.save()
        user_to_output[request.user.username] = list(student_set)
        return HttpResponseRedirect(reverse('checkerapp:validator'))
    context = {
        'callista_files': [
            f for f in CallistaDataFile.objects.all().order_by('upload_date')
        ],
    }
    return render(request, "checkerapp_process_form.html", context=context)


def convert_symbols(x):
    if len(x) < 1 or x[0] == "🟥":
        return ["Unspecified"]
    elif x[0] == "✅":
        return ["YES"]
    else:
        return x


def validator(request):
    if request.method == "POST":
        if request.user.username in user_to_output:
            output = dict()
            for student in user_to_output[request.user.username]:
                output[student] = student.validate_graduation()
            # print(output)
            df = pd.DataFrame(data={
                "student_id": map(lambda x: x.student_id, output.keys()),
                "student_name": map(lambda x: x.student_name, output.keys()),
                "course": map(lambda x: x.course.course_code, output.keys()),
                "completed_course_module": map(convert_symbols, map(lambda x: x["all_completed_cm"], output.values())),
                "pending_course_module": map(convert_symbols, map(lambda x: x["most_completed_cm"], output.values())),
                "missing_cores": map(convert_symbols, map(lambda x: x["missing_cores"], output.values())),
                "status": map(convert_symbols, map(lambda x: x["can_graduate"], output.values())),
            })
            print(df)
            df.to_csv(file_path, index=False)
            return render(request, "checkerapp_success_page.html", {'output': output})
        return HttpResponse("No student request...")
    context = {
        "students": user_to_output[request.user.username]
    }
    return render(request, "checkerapp_validate_form.html", context=context)


def download(request):
    if request.method == "POST":
        with open(file_path, 'rb') as fh:
            response = HttpResponse(
                fh.read(), content_type="text/plain")
            response['Content-Disposition'] = 'attachment; filename=' + \
                os.path.basename(file_path)
            return response
    else:
        raise Http404

checkerapp/templates/checkerapp_process_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- CSS only -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <style>
            body {
                display: flex;
                justify-content: center;
            }
            .container {
                width: 100%;
                justify-content: center;
            }
            .btn-primary {
                background-color: rgb(128, 181, 197);
                border: rgb(68, 110, 122);
            }

            .btn-primary:hover {
                background-color: rgb(124, 170, 184);
                color: white;
            }
            .btn-primary:focus {
                background-color: rgb(146, 168, 168);
            }
        </style>

        <title>Process | BoE</title>
    </head>
    <body>
        <div class="container p-5 m-5 w-100">
            <form action="{% url 'checkerapp:processor' %}" method="post">
                {% csrf_token %}
                <table class="table table-bordered w-100">
                    <thead>
                        <tr>
                            <th scope="col">Uploader</th>
                            <th scope="col">Upload Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Process</th>
                        </tr>
                    </thead>
                    {% for file in callista_files %}
                    <tr>
                        <td>{{ file.name }}</td>
                        <td>{{ file.upload_date }}</td>
                        {% if file.has_been_processed %}
                        <td>✅</td>
                        {% else %}
                        <td>Pending</td>
                        {% endif %}
                        <td>
                            <input
                                class="form-check"
                                type="checkbox"
                                name="{{file.id}}"
                                value="1"
                                unchecked
                            />
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                <input
                    class="btn btn-primary btn-lg"
                    type="submit"
                    id="process_button"
                    value="Process"
                />
            </form>
        </div>
        <script></script>
    </body>
</html>

checkerapp/templates/checkerapp_success_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <style>
            .btn-primary {
                background-color: rgb(128, 181, 197);
                border: rgb(68, 110, 122);
            }

            .btn-primary:hover {
                background-color: rgb(124, 170, 184);
                color: white;
            }

            .btn-primary:focus {
              background-color: rgb(146, 168, 168);
            }
    </style>
    <title>Result</title>
  </head>

  <div class="container m-5 mx-auto">
      <body>
        <form action="{% url 'checkerapp:download' %}" method="post">
          {% csrf_token %}
          <input class='btn btn-primary btn-lg my-3' type="submit" id="download_button" value="Download Report"/>
        </form>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Student ID</th>
              <th scope="col">Student Name</th>
              <th scope="col">Course</th>
              <th scope="col">Completed Course Modules</th>
              <th scope="col">Pending Course Module</th>
              <th scope="col">Missing Cores</th>
              {% comment %} <th scope="col">Missing Credits</th> {% endcomment %}
              <th scope="col">Completion status</th>
            </tr>
          </thead>
          <tbody>
            {% for student, my_dict in output.items %}
            <tr>
              <th scope="row">{{student.student_id}}</th>
              <td>{{student.student_name}}</td>
              <td>{{student.course.course_code}}: {{student.course.course_name}}</td>
              <td>{{ my_dict.all_completed_cm|join:", " }}</td>
              <td>{{ my_dict.most_completed_cm|join:", " }}</td>
              <td>{{ my_dict.missing_cores|join:", " }}</td>
              {% comment %} <td>{{ my_dict.missing_credits }}</td> {% endcomment %}
              <td>{{ my_dict.can_graduate|join:", " }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

checkerapp/templates/checkerapp_upload_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- CSS only -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <style>
            body,
            html {
                height: 100%;
                background-color: rgb(218, 235, 240);
            }
            .container {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100%;
            }

            .btn-primary {
                background-color: rgb(128, 181, 197);
                border: rgb(68, 110, 122);
            }

            .btn-primary:hover {
                background-color: rgb(124, 170, 184);
                color: white;
            }
            .btn-primary:focus {
                background-color: rgb(146, 168, 168);
            }
        </style>
        <title>Upload | BoE</title>
    </head>
    <body>
        <div class="container">
            <div class="center-screen">
                <div class="card shadow p-5 m-2 bg-white rounded">
                    <div class="card-body">
                        <div class="form-container">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="id_name">Name:</label>
                                    <input
                                        class="form-control form-control-lg"
                                        id="id_name"
                                        type="text"
                                        name="name"
                                        maxlength="100"
                                        required
                                    />
                                </div>

                                <div class="mb-3">
                                    <label for="id_uploads" class="form-label"
                                        >Upload your CSV files here:</label
                                    >
                                    <input
                                        class="form-control form-control-lg"
                                        name="uploads"
                                        id="id_uploads"
                                        type="file"
                                        multiple
                                        required
                                        accept=".csv"
                                    />
                                    <!-- {{ form.uploads }} -->
                                </div>
                                <div class="my-5">
                                    <a href="{% url 'checkerapp:upload' %}">
                                        <button
                                            class="btn btn-primary btn-lg w-100"
                                            type="submit"
                                        >
                                            Upload
                                        </button>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", (_) => {
                document
                    .getElementById("id_uploads")
                    .setAttribute("accept", ".csv");
            });
        </script>
        <!-- JavaScript Bundle with Popper -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

checkerapp/templates/checkerapp_validate_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <style>
        .btn-primary {
            background-color: rgb(128, 181, 197);
            border: rgb(68, 110, 122);
        }

        .btn-primary:hover {
            background-color: rgb(124, 170, 184);
            color: white;
        }
        .btn-primary:focus {
              background-color: rgb(146, 168, 168);
            }
    </style>
    <title>Validate | BoE</title>
  </head>

  <div class="container m-5 mx-auto">
      <body>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Student ID</th>
              <th scope="col">Student Name</th>
              <th scope="col">Course</th>
            </tr>
          </thead>
          <tbody>
            {% for student in students %}
            <tr>
              <th scope="row">{{student.student_id}}</th>
              <td>{{student.student_name}}</td>
              <td>{{student.course.course_code}}: {{student.course.course_name}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <form action="{% url 'checkerapp:validator' %}" method="post">
        {% csrf_token %}
        <input class='btn btn-primary btn-lg my-3' type="submit" id="validate_button" value="Validate!"/>
      </form>
  </div>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>